---
- name: ensure dependencies available through apt are installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - build-essential
    - checkinstall
    - curl
    - git
    - libcurl4-openssl-dev
    - libffi-dev
    - libgdbm-dev
    - libicu-dev
    - libncurses5-dev
    - libpq-dev
    - libreadline-dev
    - libssl-dev
    - libxml2-dev
    - libxslt-dev
    - libyaml-dev
    - logrotate
    - openssh-server
    - postgresql-9.3
    - postgresql-client 
    - python-psycopg2
    - redis-server
    - ruby2.0
    - zlib1g-dev
