---
- name: ensure that git group exists
  group:
    name: git
    state: present

- name: ensure that git user exits
  user:
    name: git
    group: git
    home: /srv/git
    createhome: yes
    comment: GitLab User
    state: present

- name: ensure gitlabhq_production database is present
  mysql_db: 
    name: gitlabhq_production

- name: ensure git database user is present
  mysql_user: 
    name: git
    host: "{{ item }}" 
    password: "{{ git_mysql_password }}" 
    priv: gitlabhq_production.*:ALL
  with_items:
    - "%"
    - localhost

- name: check gitlab out of git repository
  sudo_user: git
  git:
    repo: https://gitlab.com/gitlab-org/gitlab-ce.git
    dest: /srv/git/gitlab
    update: yes

- name: ensure log directory exists and has correct permissions
  file:
    path: /srv/git/gitlab/log
    owner: git
    group: git
    recurse: yes
    mode: 700
    state: directory

- name: ensure tmp directory exists and has correct permissions
  file:
    path: /srv/git/gitlab/tmp
    owner: git
    group: git
    recurse: yes
    mode: 700
    state: directory

- name: ensure tmp/pids directory exists and has correct permissions
  file:
    path: /srv/git/gitlab/tmp/pids
    owner: git
    group: git
    recurse: yes
    mode: 700
    state: directory

- name: ensure tmp/sockets directory exists and has correct permissions
  file:
    path: /srv/git/gitlab/tmp/sockets
    owner: git
    group: git
    recurse: yes
    mode: 700
    state: directory

- name: ensure satellites directory exists and has correct permissions
  file:
    path: /srv/git/gitlab-satellites
    owner: git
    group: git
    recurse: yes
    mode: 750
    state: directory

- name: bundle install ruby gems
  sudo_user: git
  command: bundle install --deployment --without development test postgresql aws 
           chdir=/srv/git/gitlab
