---
- name: ensure dependencies available through apt are installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - build-essential
    - bundler
    - checkinstall
    - curl
    - git
    - libcurl4-openssl-dev
    - libffi-dev
    - libgdbm-dev
    - libicu-dev
    - libmariadbclient-dev
    - libncurses5-dev
    - libreadline-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - logrotate
    - redis-server
    - ruby
    - ruby-dev
    - zlib1g-dev
    - libyaml-dev

- name: ensure that git group exists
  group:
    name: git
    state: present

- name: ensure that git user exits
  user:
    name: git
    group: git
    home: /home/git
    createhome: yes
    shell: /bin/bash
    comment: GitLab User
    state: present

- name: ensure link to /srv/git exists
  file:
    path: /srv/git
    src: /home/git
    force: yes
    state: link

- name: ensure gitlabhq_production database is present
  mysql_db: 
    name: gitlabhq_production

- name: ensure git database user is present
  mysql_user: 
    name: git
    host: "{{ item }}" 
    password: "{{ gitlab_git_mysql_password }}" 
    priv: gitlabhq_production.*:ALL
  with_items:
    - "%"
    - localhost

- name: update /home/git/.my.cnf from template
  template:
    src: home/git/.my.cnf
    dest: /home/git/.my.cnf
    owner: git
    group: git
    mode: 0600

- name: ensure /home/git/gitlab exists and has correct permissions
  file:
    path: /home/git/gitlab
    owner: git
    group: git
    recurse: no
    mode: 0755
    state: directory

- name: check gitlab out of git repository
  sudo_user: git
  git:
    repo: https://gitlab.com/gitlab-org/gitlab-ce.git
    dest: /home/git/gitlab
    update: yes
    force: no
  notify:
    - restart gitlab

- name: ensure /home/git/gitlab/log exists and has correct permissions
  file:
    path: /home/git/gitlab/log
    owner: git
    group: git
    recurse: yes
    mode: 0700
    state: directory

- name: ensure /home/git/gitlab/tmp exists and has correct permissions
  file:
    path: /home/git/gitlab/tmp
    owner: git
    group: git
    recurse: yes
    mode: 0755
    state: directory

- name: ensure /home/git/gitlab/tmp/pids exists and has correct permissions
  file:
    path: /home/git/gitlab/tmp/pids
    owner: git
    group: git
    recurse: yes
    mode: 0700
    state: directory

- name: ensure /home/git/gitlab/tmp/sockets exists and has correct permissions
  file:
    path: /home/git/gitlab/tmp/sockets
    owner: git
    group: git
    recurse: yes
    mode: 0755
    state: directory

- name: ensure /home/git/gitlab-satellites exists and has correct permissions
  file:
    path: /home/git/gitlab-satellites
    owner: git
    group: git
    recurse: yes
    mode: 0750
    state: directory

- name: ensure /home/git/repositories exists and has correct permissions
  file:
    path: /home/git/repositories
    owner: git
    group: git
    recurse: yes
    mode: 0700
    state: directory

- name: ensure /home/git/repositories/root exists and has correct permissions
  file:
    path: /home/git/repositories/root
    owner: git
    group: git
    recurse: yes
    mode: 0700
    state: directory

- name: update gitlab.yml from template
  template:
    src: home/git/gitlab/config/gitlab.yml
    dest: /home/git/gitlab/config/gitlab.yml
    owner: git
    group: git
    mode: 0600
  notify:
    - restart gitlab

- name: update database.yml from template
  template:
    src: home/git/gitlab/config/database.yml
    dest: /home/git/gitlab/config/database.yml
    owner: git
    group: git
    mode: 0600
  notify:
    - restart gitlab

- name: update unicorn.rb from template
  template:
    src: home/git/gitlab/config/unicorn.rb
    dest: /home/git/gitlab/config/unicorn.rb
    owner: git
    group: git
    mode: 0600
  notify:
    - restart gitlab

- name: bundle install ruby gems
  sudo_user: git
  command: bundle install --deployment --without development test postgres aws
           chdir=/home/git/gitlab
  register: bundle_install
  changed_when: bundle_install.stdout.find("Installing") != -1
  notify:
    - restart gitlab

- name: configure gitlab shell
  sudo_user: git
  command: bundle exec rake gitlab:shell:install[v1.9.3] REDIS_URL=redis://localhost:6379 RAILS_ENV=production
           chdir=/home/git/gitlab
           creates=/home/git/.ssh/authorized_keys
  notify:
    - restart gitlab

- name: compile assets if necessary
  sudo_user: git
  command: bundle exec rake assets:precompile RAILS_ENV=production
           chdir=/home/git/gitlab
  register: rake_assets_precompile
  changed_when: bundle_install.stdout.find("Writing") != -1
  notify:
    - restart gitlab

- name: set up database if necessary 
  sudo_user: git
  shell: bundle exec rake gitlab:setup RAILS_ENV=production <<< "yes" && touch ../.setup_database
         executable=/bin/bash
         chdir=/home/git/gitlab
         creates=/home/git/.setup_database
  notify:
    - restart gitlab

- name: ensure /etc/init.d/gitlab exists and links to /home/git/gitlab/lib/support/init.d/gitlab
  file:
    path: /etc/init.d/gitlab
    src: /home/git/gitlab/lib/support/init.d/gitlab
    force: yes
    state: link

- name: ensure /etc/default/gitlab exists and links to /home/git/gitlab/lib/support/init.d/gitlab.default.example
  file:
    path: /etc/default/gitlab
    src: /home/git/gitlab/lib/support/init.d/gitlab.default.example
    force: yes
    state: link

- name: ensure /etc/logrotate.d/gitlab exists and links to /home/git/gitlab/lib/support/logrotate/gitlab
  file:
    path: /etc/logrotate.d/gitlab
    src: /home/git/gitlab/lib/support/logrotate/gitlab
    force: yes
    state: link

- name: ensure gitlab is started and enabled
  service:
    name: gitlab
    state: started
    enabled: yes

- name: update /etc/nginx/sites-available/gitlab from template
  template:
    src: etc/nginx/sites-available/gitlab
    dest: /etc/nginx/sites-available/gitlab
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx

- name: ensure /etc/nginx/sites-enabled/gitlab exists and links to ../sites-available/gitlab
  file:
    path: /etc/nginx/sites-enabled/gitlab
    src: ../sites-available/gitlab
    force: yes
    state: link
  notify:
    - restart nginx

