---
#- include: docker.yml
#  when: mariadb_dockerized_deployment

- include: install.yml
  when: not gitlab_dockerized_deployment

#- include: configure.yml
#  when: not gitlab_dockerized_deployment 
