---
- name: ensure postgresql packages are installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - libpq-dev
    - postgresql-9.3
    - postgresql-client 
    - python-psycopg2

- name: ensure that git postgresql user exits
  postgresql_user:
    name: git
    role_attr_flags: CREATEDB
    state: present
    
- name: ensure that gitlab postgresql database exists
  postgresql_db:
    name: gitlabhq_production
    owner: git
    template: template1
    state: present
