production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gitlabhq_production
  pool: 10
  host: "{{ gitlab_mysql_host }}"
  username: git
  password: "{{ gitlab_git_mysql_password }}"
