production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gitlabhq_production
  pool: 10
  username: "{{ gitlab_mysql_user }}"
  password: "{{ gitlab_mysql_password }}"
  host: "{{ gitlab_mysql_host }}"
  # socket: /tmp/mysql.sock
